USE [master]
GO

/****** Object:  Database [Manutencao]    Script Date: 03/02/2020 16:25:55 ******/
CREATE DATABASE [Manutencao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Manutencao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Manutencao.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Manutencao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Manutencao_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Manutencao] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Manutencao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Manutencao] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Manutencao] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Manutencao] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Manutencao] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Manutencao] SET ARITHABORT OFF 
GO

ALTER DATABASE [Manutencao] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Manutencao] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Manutencao] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Manutencao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Manutencao] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Manutencao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Manutencao] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Manutencao] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Manutencao] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Manutencao] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Manutencao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Manutencao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Manutencao] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Manutencao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Manutencao] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Manutencao] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Manutencao] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Manutencao] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Manutencao] SET  MULTI_USER 
GO

ALTER DATABASE [Manutencao] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Manutencao] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Manutencao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Manutencao] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Manutencao] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Manutencao] SET  READ_WRITE 
GO

